/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RedeemRequest {
  'id' : bigint,
  'status' : RedeemStatus,
  'userName' : string,
  'userEmail' : string,
  'code' : string,
  'userId' : Principal,
  'coins' : bigint,
  'rewardType' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type RedeemStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'dailyAdsWatched' : bigint,
  'coins' : bigint,
  'lastAdDate' : string,
  'lastRedeemTime' : bigint,
  'fastClickCount' : bigint,
  'nextAllowedAdTime' : bigint,
  'fastClickDisabledUntil' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Admin: Manual coin adjustment for user
   */
  'adjustUserCoins' : ActorMethod<[Principal, bigint], UserProfile>,
  /**
   * / Approve a redeem request (admin only)
   */
  'approveRedeemRequest' : ActorMethod<[bigint], [] | [RedeemRequest]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Earn coins by watching an ad - with cooldown checks
   */
  'earnCoins' : ActorMethod<[], UserProfile>,
  /**
   * / Get all redeem requests (admin only)
   */
  'getAllRedeemRequests' : ActorMethod<[], Array<RedeemRequest>>,
  /**
   * / Admin: Get all user profiles (admin only)
   */
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  /**
   * / Returns the current user's profile, creating it if it doesn't exist
   */
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Utility: Get current date (YYYY-MM-DD)
   */
  'getCurrentDateTimestamp' : ActorMethod<[], bigint>,
  /**
   * / Admin: Get user profile by Principal (admin only)
   */
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  /**
   * / Get user's redeem history
   */
  'getUserRedeemHistory' : ActorMethod<[], Array<RedeemRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Reject a redeem request (admin only)
   */
  'rejectRedeemRequest' : ActorMethod<[bigint], [] | [RedeemRequest]>,
  /**
   * / Submit a redeem request for coins
   */
  'submitRedeemRequest' : ActorMethod<[bigint, string, string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];