/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserProfile = IDL.Record({
  'dailyAdsWatched' : IDL.Nat,
  'coins' : IDL.Nat,
  'lastAdDate' : IDL.Text,
  'lastRedeemTime' : IDL.Int,
  'fastClickCount' : IDL.Nat,
  'nextAllowedAdTime' : IDL.Int,
  'fastClickDisabledUntil' : IDL.Int,
});
export const RedeemStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const RedeemRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RedeemStatus,
  'userName' : IDL.Text,
  'userEmail' : IDL.Text,
  'code' : IDL.Text,
  'userId' : IDL.Principal,
  'coins' : IDL.Nat,
  'rewardType' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustUserCoins' : IDL.Func([IDL.Principal, IDL.Nat], [UserProfile], []),
  'approveRedeemRequest' : IDL.Func([IDL.Nat], [IDL.Opt(RedeemRequest)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'earnCoins' : IDL.Func([], [UserProfile], []),
  'getAllRedeemRequests' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentDateTimestamp' : IDL.Func([], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserRedeemHistory' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectRedeemRequest' : IDL.Func([IDL.Nat], [IDL.Opt(RedeemRequest)], []),
  'submitRedeemRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserProfile = IDL.Record({
    'dailyAdsWatched' : IDL.Nat,
    'coins' : IDL.Nat,
    'lastAdDate' : IDL.Text,
    'lastRedeemTime' : IDL.Int,
    'fastClickCount' : IDL.Nat,
    'nextAllowedAdTime' : IDL.Int,
    'fastClickDisabledUntil' : IDL.Int,
  });
  const RedeemStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const RedeemRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RedeemStatus,
    'userName' : IDL.Text,
    'userEmail' : IDL.Text,
    'code' : IDL.Text,
    'userId' : IDL.Principal,
    'coins' : IDL.Nat,
    'rewardType' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustUserCoins' : IDL.Func([IDL.Principal, IDL.Nat], [UserProfile], []),
    'approveRedeemRequest' : IDL.Func([IDL.Nat], [IDL.Opt(RedeemRequest)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'earnCoins' : IDL.Func([], [UserProfile], []),
    'getAllRedeemRequests' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentDateTimestamp' : IDL.Func([], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserRedeemHistory' : IDL.Func([], [IDL.Vec(RedeemRequest)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectRedeemRequest' : IDL.Func([IDL.Nat], [IDL.Opt(RedeemRequest)], []),
    'submitRedeemRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };