/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Notice {
    id: bigint;
    title: string;
    message: string;
    timestamp: bigint;
}
export interface RedeemRequest {
    id: bigint;
    status: RedeemStatus;
    userName: string;
    userEmail: string;
    code: string;
    userId: Principal;
    coins: bigint;
    rewardType: string;
    timestamp: bigint;
    amount: bigint;
}
export interface UserProfile {
    dailyAdsWatched: bigint;
    coins: bigint;
    lastAdDate: string;
    lastRedeemTime: bigint;
    fastClickCount: bigint;
    nextAllowedAdTime: bigint;
    fastClickDisabledUntil: bigint;
}
export enum RedeemStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Admin: Manual coin adjustment
     */
    adjustUserCoins(user: Principal, coins: bigint): Promise<UserProfile>;
    /**
     * / Approve a redeem request
     */
    approveRedeemRequest(requestId: bigint): Promise<RedeemRequest | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Delete a notice
     */
    deleteNotice(id: bigint): Promise<boolean>;
    /**
     * / Earn coins by watching an ad - with cooldown checks
     */
    earnCoins(): Promise<UserProfile>;
    /**
     * / Edit a notice
     */
    editNotice(id: bigint, title: string, message: string): Promise<Notice | null>;
    /**
     * / Get all notices (public)
     */
    getAllNotices(): Promise<Array<Notice>>;
    /**
     * / Get all redeem requests (admin)
     */
    getAllRedeemRequests(): Promise<Array<RedeemRequest>>;
    /**
     * / Admin: Get all user profiles
     */
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    /**
     * / Returns the current user's profile
     */
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Utility: Get current date timestamp
     */
    getCurrentDateTimestamp(): Promise<bigint>;
    /**
     * / Get total user count
     */
    getTotalUserCount(): Promise<bigint>;
    /**
     * / Admin: Get user profile by Principal
     */
    getUserProfile(user: Principal): Promise<UserProfile>;
    /**
     * / Get user's own redeem history
     */
    getUserRedeemHistory(): Promise<Array<RedeemRequest>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Post a new notice (admin validated in frontend)
     */
    postNotice(title: string, message: string): Promise<Notice>;
    /**
     * / Reject a redeem request
     */
    rejectRedeemRequest(requestId: bigint): Promise<RedeemRequest | null>;
    /**
     * / Submit a redeem request
     */
    submitRedeemRequest(amount: bigint, rewardType: string, userName: string, userEmail: string): Promise<string>;
}
import type { Notice as _Notice, RedeemRequest as _RedeemRequest, RedeemStatus as _RedeemStatus, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adjustUserCoins(arg0: Principal, arg1: bigint): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustUserCoins(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustUserCoins(arg0, arg1);
            return result;
        }
    }
    async approveRedeemRequest(arg0: bigint): Promise<RedeemRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRedeemRequest(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRedeemRequest(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteNotice(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async earnCoins(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.earnCoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.earnCoins();
            return result;
        }
    }
    async editNotice(arg0: bigint, arg1: string, arg2: string): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.editNotice(arg0, arg1, arg2);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editNotice(arg0, arg1, arg2);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return result;
        }
    }
    async getAllRedeemRequests(): Promise<Array<RedeemRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRedeemRequests();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRedeemRequests();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentDateTimestamp(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentDateTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentDateTimestamp();
            return result;
        }
    }
    async getTotalUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUserCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return result;
        }
    }
    async getUserRedeemHistory(): Promise<Array<RedeemRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRedeemHistory();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRedeemHistory();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postNotice(arg0: string, arg1: string): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.postNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postNotice(arg0, arg1);
            return result;
        }
    }
    async rejectRedeemRequest(arg0: bigint): Promise<RedeemRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRedeemRequest(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRedeemRequest(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRedeemRequest(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRedeemRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRedeemRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_RedeemRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedeemRequest): RedeemRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RedeemStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedeemStatus): RedeemStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RedeemRequest]): RedeemRequest | null {
    return value.length === 0 ? null : from_candid_RedeemRequest_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RedeemStatus;
    userName: string;
    userEmail: string;
    code: string;
    userId: Principal;
    coins: bigint;
    rewardType: string;
    timestamp: bigint;
    amount: bigint;
}): {
    id: bigint;
    status: RedeemStatus;
    userName: string;
    userEmail: string;
    code: string;
    userId: Principal;
    coins: bigint;
    rewardType: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RedeemStatus_n4(_uploadFile, _downloadFile, value.status),
        userName: value.userName,
        userEmail: value.userEmail,
        code: value.code,
        userId: value.userId,
        coins: value.coins,
        rewardType: value.rewardType,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RedeemStatus {
    return "pending" in value ? RedeemStatus.pending : "approved" in value ? RedeemStatus.approved : "rejected" in value ? RedeemStatus.rejected : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RedeemRequest>): Array<RedeemRequest> {
    return value.map((x)=>from_candid_RedeemRequest_n2(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
